import { StyleSheet } from 'react-native';
import type { Palette } from '../../theme';

// Dense, utilitarian layout for the developer performance lab. The entire screen
// scrolls, while the results console has its own bounded scroll region.
export const makeStyles = (p: Palette) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: p.background },
    scrollContent: { paddingTop: 56, paddingHorizontal: 16, paddingBottom: 48 },
    eyebrow: {
      color: p.primary,
      fontFamily: 'JetBrainsMono_500Medium',
      fontSize: 11,
      lineHeight: 15,
      letterSpacing: 1,
      marginBottom: 6,
      textTransform: 'uppercase',
    },
    title: {
      color: p.text,
      fontFamily: 'DMSans_600SemiBold',
      fontSize: 22,
      lineHeight: 28,
      marginBottom: 6,
    },
    hint: {
      color: p.textMuted,
      fontFamily: 'DMSans_400Regular',
      fontSize: 13,
      lineHeight: 19,
    },
    status: {
      alignSelf: 'flex-start',
      backgroundColor: p.primarySoft,
      borderRadius: 999,
      color: p.text,
      fontFamily: 'DMSans_600SemiBold',
      fontSize: 12,
      lineHeight: 16,
      marginTop: 12,
      overflow: 'hidden',
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    section: { marginTop: 24 },
    sectionTitle: {
      color: p.text,
      fontFamily: 'DMSans_600SemiBold',
      fontSize: 16,
      lineHeight: 21,
      marginBottom: 4,
    },
    sectionHint: {
      color: p.textMuted,
      fontFamily: 'DMSans_400Regular',
      fontSize: 12,
      lineHeight: 17,
      marginBottom: 10,
    },
    itinerary: {
      backgroundColor: p.surfaceSunk,
      borderColor: p.border,
      borderRadius: 10,
      borderWidth: 1,
      padding: 12,
    },
    itineraryItem: { flexDirection: 'row', gap: 10, paddingVertical: 7 },
    itineraryNumber: {
      backgroundColor: p.primary,
      borderRadius: 12,
      color: p.onPrimary,
      fontFamily: 'JetBrainsMono_500Medium',
      fontSize: 11,
      height: 24,
      lineHeight: 24,
      overflow: 'hidden',
      textAlign: 'center',
      width: 24,
    },
    itineraryBody: { flex: 1 },
    itineraryTitle: {
      color: p.text,
      fontFamily: 'DMSans_600SemiBold',
      fontSize: 13,
      lineHeight: 18,
    },
    itineraryDescription: {
      color: p.textMuted,
      fontFamily: 'DMSans_400Regular',
      fontSize: 12,
      lineHeight: 17,
      marginTop: 1,
    },
    actionCard: {
      backgroundColor: p.surface,
      borderColor: p.border,
      borderRadius: 10,
      borderWidth: 1,
      marginBottom: 10,
      padding: 12,
    },
    actionOrder: {
      color: p.primary,
      fontFamily: 'JetBrainsMono_500Medium',
      fontSize: 10,
      lineHeight: 14,
      marginBottom: 7,
      textTransform: 'uppercase',
    },
    actionDescription: {
      color: p.textMuted,
      fontFamily: 'DMSans_400Regular',
      fontSize: 12,
      lineHeight: 17,
      marginTop: 8,
    },
    stepValue: {
      color: p.text,
      fontFamily: 'JetBrainsMono_500Medium',
      fontSize: 14,
      lineHeight: 19,
      marginBottom: 10,
      textAlign: 'center',
    },
    stepButtons: { flexDirection: 'row', gap: 10 },
    stepButton: { flex: 1 },
    selectedDocument: {
      color: p.success,
      fontFamily: 'DMSans_600SemiBold',
      fontSize: 12,
      lineHeight: 17,
      marginBottom: 10,
    },
    emptyDocuments: {
      color: p.textDim,
      fontFamily: 'DMSans_400Regular',
      fontSize: 12,
      lineHeight: 17,
      paddingVertical: 8,
    },
    logBox: {
      backgroundColor: p.surfaceSunk,
      borderColor: p.borderStrong,
      borderRadius: 10,
      borderWidth: 1,
      height: 360,
      padding: 12,
    },
    logText: {
      color: p.text,
      fontFamily: 'JetBrainsMono_500Medium',
      fontSize: 11,
      lineHeight: 16,
    },
  });
